version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nest_auth
      MYSQL_USER: nest_user
      MYSQL_PASSWORD: nest_password
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql

  app:
    image: node:22-alpine
    container_name: nest-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: nest_user
      DB_PASSWORD: nest_password
      DB_NAME: nest_auth

volumes:
  dbdata: